name: Testing the release before pushing on Pypi

on:
  push:
    branches:
      - dev

jobs:
  basic_bash:
    name: Testing some function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Dynamically Extracted the data
      run: bash bin/rc.sh ${{ github.event.head_commit.message }}

    - name: print the create release
      run: echo $CREATE_RELEASE && echo $package_version

#    - name: get the commit_message
#      run: python -m pip install --upgrade pip
#
#    - name: Install build dependencies
#      run: python -m pip install setuptools twine build
