name: Testing the release before pushing on Pypi

on:
  push:
    branches:
      - dev

jobs:
  basic_bash:
    name: Testing some function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Extract the version from commit_message
      run: |
        echo "CREATE_RELEASE=0" >> $GITHUB_ENV
        pattern="^release-([0-9]+.[0-9]+\.[0-9]+)"
        commit_message=${{ github.event.head_commit.message }}
        if [[ $commit_message =~ $pattern ]]; then
          package_version="${BASH_REMATCH[1]}"
          echo "package_version=$package_version" >> $GITHUB_ENV
          echo "CREATE_RELEASE=1" >> $GITHUB_ENV
        fi

    - name: change the version in file
      run: |
        project_file="${PWD}/pyproject.toml"
        project_version=${{ env.package_version }}
        is_release=${{ env.package_version }}
        if [[ "${is_release}" == "1" ]]; then
          sed -i "s/version = \".*\"/version = \"${project_version}\"/" $project_file
        fi

    - name: validate file
      run: |
        cat "${PWD}/pyproject.toml"
